version: '3.9'
services:
  app:
    image: ghcr.io/jmorton95/raw-backend:d25b00ae90e36ce93c5b1cb5291a8c3d1f77460d
    secrets:
      - db-password
    ports:
      - "80:8080"
    environment:
       - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=postgres;Username=postgres;Password_FILE=/run/secrets/db-password;Include Error Detail=true
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  db:
    image: postgres:15.2
    user: postgres
    secrets:
    - db-password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  migrate:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine
    secrets:
      - db-password
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=postgres;Username=postgres;Password_FILE=/run/secrets/db-password;Include Error Detail=true
    entrypoint: ["dotnet", "ef", "database", "update"]
   
volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    external: true