version: '3.9'
services:
  app:
    container_name: raw-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings_DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=postgres;"
    networks:
      - app_network
  db:
    container_name: db
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
volumes:
  pgdata: {}
networks:
  app_network: {}