services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=josh@rawengineering.net"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.tcp.address=:5432"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      - mode: host
        protocol: tcp
        published: 5432
        target: 5432
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.middlewares.redirect-www.redirectregex.regex=^www\\.(.*)"
      - "traefik.http.middlewares.redirect-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-www.redirectregex.permanent=true"
      - "traefik.http.routers.www-router.rule=Host(`www.rawengineering.net`)"
      - "traefik.http.routers.www-router.entrypoints=websecure"
      - "traefik.http.routers.www-router.tls=true"
      - "traefik.http.routers.www-router.tls.certresolver=myresolver"
      - "traefik.http.routers.www-router.tls.domains[0].main=rawengineering.net"
      - "traefik.http.routers.www-router.tls.domains[0].sans=www.rawengineering.net"
      - "traefik.http.routers.www-router.middlewares=redirect-www"

  app:
    image: ghcr.io/jmorton95/raw-backend:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.rule=Host(`rawengineering.net`, `www.rawengineering.net`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    environment:
      - DatabaseSettings__Host=db
      - DatabaseSettings__Port=5432
      - DatabaseSettings__Database=raw-backend
      - DatabaseSettings__Username=postgres
      - DatabaseSettings__Password=${DB_PASSWORD}
      - ThirdParty__ApiClientId=${API_CLIENT_ID}
      - ThirdParty__ApiClientSecret=${API_CLIENT_SECRET}
      - ThirdParty__ApiClientAuthUrl=${API_CLIENT_AUTH_URL}
      - ThirdParty__ValidationToken=${VALIDATION_TOKEN}
      - ThirdParty__HostedEndpoint=${HOSTED_ENDPOINT}
      - ThirdParty__ElectedSellerId=${ELECTED_SELLER_ID}
      - ThirdParty__ProductQueryUrl=${PRODUCT_QUERY_URL}
      - ThirdParty__ProductFilterString=${PRODUCT_FILTER_STRING}
      - ThirdParty__ProductMarketplaceId=${PRODUCT_MARKETPLACE_ID}
      - ThirdParty__GrantType=${GRANT_TYPE}
      - ThirdParty__Scopes=${SCOPES}
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db

  db:
    image: postgres:17.2
    user: postgres
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entrypoints=tcp"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  letsencrypt:

secrets:
  db-password:
    external: true
